apiVersion: apps/v1
kind: Deployment
metadata:
  name: crud-api-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud-api-operator
  template:
    metadata:
      labels:
        app: crud-api-operator
    spec:
      serviceAccountName: crud-api-operator
      containers:
        - name: crud-api-operator
          image: your-operator-image:tag
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: crud-api-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps", "secrets", "customresourcedefinitions"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: crud-api-operator-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: crud-api-operator-role
subjects:
  - kind: ServiceAccount
    name: crud-api-operator
    namespace: default
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: crud-api-operator
