apiVersion: v1
kind: Service
metadata:
  name: {{ include "mongodb.fullname" . }}
  labels:
    app: {{ include "mongodb.name" . }}
spec:
  selector:
    app: {{ include "mongodb.name" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
